### ISSUE TITLE
source sans pro font instead?

### ISSUE THREAD

**Issue by ahjolinna** [erikdubois/Aureola#1]
I have never been that big of fan of ubuntu font, I have been using [Adobe's Source sans pro](http://adobe-fonts.github.io/source-sans-pro/) [&other versions](https://github.com/adobe-fonts), I also notice that Jolla uses this font also on SailfishOS (forked version)

I tried to directly to replace that ubuntu font but it didnt fit that well with the current setup (font size at least)

**Comment by erikdubois** [comment]
used your font idea in acros
