### ISSUE TITLE
hi erik spotter help

### ISSUE THREAD

**Issue by tjw0lf** [erikdubois/Aureola#11]
Its TJ Wolf  erikdubois Thanks for the conky i need help running it. Mine doesn't look transparent werid and glitchei can you help please

Can you help me get spotify for manjaro Arch i seem to get errors trying to install

**Comment by erikdubois** [comment]
regarding spotify - you can report issues with installation on the aur on archlinux
that is what I would do next to googling your issue

**Comment by erikdubois** [comment]
transparency
check out this part of the conky
	own_window = true,
	own_window_argb_value = 150, ------ YOU CAN CHANGE THIS ONE
	own_window_argb_visual = true,
	own_window_class = 'Conky',
	own_window_colour = '#000000',
	own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
	own_window_transparent = no,
	own_window_title = 'system_conky',
	own_window_type = 'normal',-- # options are: normal/override/dock/desktop/panel ------ YOU CAN CHANGE THIS ONE

Depending on the window manager you should try the combinations of both lines.

**Comment by tjw0lf** [comment]
the spotify thing i found workaround but you need to login as facebook via. but i tried all and wouldn't go transpernet in manjaro KDE 16.10.3 is what i'm using. also can you fix your conkys so there compatble with conky manager if you can please. then conkys will work

**Comment by tjw0lf** [comment]
WHY DID YOU CLOSE THIS

**Comment by erikdubois** [comment]
because it is up to you to figure out what possible combinations you can try
own_window_type = 'normal',-- # options are: normal/override/dock/desktop/panel 
try any of these

own_window_argb_value = 150, 

change the number to 0 - transparent or 255 opaque

**Comment by tjw0lf** [comment]
Oh i didn't know that. You should have stated that for your conkys. Thanks. 

Also how do i use the phantom conky  i get error in terminal says something about dropbox do i need to install something. These things should be instructions on front page if so.

Also can you make these compatible with conky manager

**Comment by tjw0lf** [comment]
I don't see this in spotter conky

own_window_argb_value = 150,

change the number to 0 - transparent or 255 opaque

**Comment by tjw0lf** [comment]
Can you help me please

**Comment by erikdubois** [comment]
check the conky's code again - should be fixed now
