### ISSUE TITLE
Hi erikdubois

### ISSUE THREAD

**Issue by tjw0lf** [erikdubois/Aureola#15]
How can i auto start the spotter conky please. I have another in conky manager and tried to put the start_conky.desktop in autostart and turn on conky from conky manager but the conky in conky manager just start and not spotter. Is there a way you put the spotter in conky manager to see it or autostart it with conky from conky manager. 

Please help erik dubois
Thank you

**Comment by erikdubois** [comment]
to my knowledge (tried it out on archlabs) conky manager is not yet compatible with the new lua configuration. check what version of conky you have
aureola needs version >1.10
in terminal
conky --version  
(scroll back to top)

**Comment by tjw0lf** [comment]
is there another way to have the spotter auto start on login. with another conky i have running on startup in conky manager.

**Comment by erikdubois** [comment]
it all depends your conky's must speak the same language i.e. lua is version >1.10 or non lua is version <1.10
you can not have both conky version on the same system
what version do you have?
To know what lua is ... open one of my conky.conf files of aureola

**Comment by tjw0lf** [comment]
erikdubois can you do this one for clementine  i would love you for it if you hook me up i with this i will throw you some cash :dancing_men:  
http://forum.learnfree.eu/viewtopic.php?f=9&t=422&start=75


It seems spotter one for spotify doesn't work with Clementine using spotify plugin thats why i want it just like in the pic

**Comment by erikdubois** [comment]
you can always try the following code lines in a startup script or put them in .bashrc and tell me what happens

conky -c -q ~/.aureola/acros/conky.conf
conky -c -q ~/.aureola/cherry/conky.conf

**Comment by tjw0lf** [comment]
erikdubois can you do this one for clementine i would love you for it if you hook me up i with this i will throw you some cash :dancing_men:
http://forum.learnfree.eu/viewtopic.php?f=9&t=422&start=75

It seems spotter one for spotify doesn't work with Clementine using spotify plugin thats why i want it just like in the pic

**Comment by tjw0lf** [comment]
READ^^

**Comment by erikdubois** [comment]
do you mean making a conky that gets its information from clementine and gets the image as well....?

**Comment by erikdubois** [comment]
conky -c ~/.aureola/acros/conky.conf -q
conky -c ~/.aureola/cherry/conky.conf -q

This will work if you can get it to autostart at boot then you succeeded but NOT in .bashrc (only used if a terminal is started).

**Comment by tjw0lf** [comment]
Yeas please Thank you. 
I put link in above^^  it shows the one i want how to look i think its outdated tho. it has configfile.tar.gz have a look

**Comment by tjw0lf** [comment]
I will try those commands Thank you keep up awesome work :+1:

**Comment by erikdubois** [comment]
there is a lot when i follow the link AND it is in Russian...?

**Comment by erikdubois** [comment]
first hit on google 
https://tycho.ws/blog/2010/10/conky-clementine.html

quote from another site

Thanks! But there is an easier way to access metadata of the played track (cover included), and without any variable. Type in a terminal: qdbus org.mpris.clementine /Player org.freedesktop.MediaPlayer.GetMetadata And we can also control Clementine; see the result of this command: qdbus org.mpris.clementine /Player That's all! :)

maybe this one can help you...

https://github.com/diadara/conky-clementine

Did you try figuring it out yourself yet?

**Comment by tjw0lf** [comment]
yes i did i don't know how. But it was this one i wanted like. If you can help me out. it has the conky config tar.gz under it. I just don't know what to do if you can help be most Appreciated Thank you 

http://i.imgur.com/mWL3XlP.png

**Comment by tjw0lf** [comment]
Hi erik can you fix your spotify ones from your forge accout please i like those ones with the big covers and stuff

**Comment by erikdubois** [comment]
aurora is dead and making a zombie out of it is not my priority ;-)

**Comment by tjw0lf** [comment]
Can you please update your spotify ones from your froge

**Comment by erikdubois** [comment]
froge ??

**Comment by tjw0lf** [comment]
https://sourceforge.net/projects/auroraconkytheme/

spotify ones from here. i like large xxl cover BIG fix please

**Comment by erikdubois** [comment]
I have to divide my free time over some projects. aurora is dead for me and aureola is the successor.
