### ISSUE TITLE
STOP closing my ticket and  talk to me dude

### ISSUE THREAD

**Issue by tjw0lf** [erikdubois/Aureola#17]
I have to divide my free time over some projects. aurora is dead for me and aureola is the successor.
It has also a spotify cover.

I just want the spotify cover xxl like you did in the others in past

**Comment by erikdubois** [comment]
it nice that you want that.

**Comment by tjw0lf** [comment]
Sorry erik dubois. i was being rude again. Your nice's person  coolest script editor i know. If you can't do it its ok. I'm good now Matt hook me up with hes mods..
