### ISSUE TITLE
conky spotter not showing coverz anymore

### ISSUE THREAD

**Issue by tjw0lf** [erikdubois/Aureola#18]
How can i fix this again my great friend erikdubois.

I'm on manjaro 17 xfce

**Comment by tjw0lf** [comment]
OK weird......
i figured it out manjaro Arch xfce. seems wget wasn't installed. But was the weird part is couple covers where showing. manjaro leaving alot packages out. I might have to move to Archlabs with you my friend.

wait did you list that we needed to install wget be any chance. you should put it in your script for Arch users

**Comment by erikdubois** [comment]
wget is part of the core applications if i am not mistaken.
guessing something has gone wrong in the past with a pacman -R
closing for now
come aboard - #archlabs is awesome 
releasing an article today about archlabs 4.0
http://erikdubois.be/
