### ISSUE TITLE
distro/DE logo?

### ISSUE THREAD

**Issue by ahjolinna** [erikdubois/Aureola#2]
it would be nice if this conky conf would have the distro or DE logo after the distro name (detection)

**Comment by erikdubois** [comment]
no detection yet... check out acros

**Comment by ahjolinna** [comment]
there was something called openlogos font that had most of the distros and DE and other logos...I dont know where its anymore, I used it for my old conky conf (kde4 times)

**Comment by ahjolinna** [comment]
only thing that I found of openlogos font was this in [aur](https://aur.archlinux.org/packages/ttf-openlogos-archupdate/)

**Comment by ahjolinna** [comment]
I found a project that is called "[nerd fonts](https://nerdfonts.com/)", the [aur link](https://aur.archlinux.org/packages/nerd-fonts-complete/) ..could be at least useful for this and maybe some other stuff as its quite extensive

**Comment by ghost** [comment]
How can I change the mint logo to a debian logo? Thx a lot.

**Comment by ghost** [comment]
Theme acros still does not detect debian. The icon remains a mint one :(

**Comment by ghost** [comment]
Theme acros still does not detect debian. The icon remains a mint one :(

**Comment by ghost** [comment]
Another issue I have had is that the themes take up all my desktop and hid my wallpaper. It would be good if I could choose the themes background with nitrogen. As I do in my Tiling WM and start it on login with the command "nitrogen --replace". So that in the "conky.conf" file I could put something like:
background = "nitrogen --replace"
;)

**Comment by erikdubois** [comment]
there is no auto detection - change manually

**Comment by trane77** [comment]
Hello, I've imported a custom logo image, sizing it to 128x128 png. 
If I switch to other logos already present, it works, but with my image not. 

I did some tests, removing transparency, changing name format... nothing worked. Any hints ? thanks

**Comment by erikdubois** [comment]
support has stopped
