### ISSUE TITLE
No temp, download, upload values for Asura theme

### ISSUE THREAD

**Issue by foo4foo** [erikdubois/Aureola#20]
This is my screenshot. I'm currently on Manjaro 17.06 XFCE (AMD X4 860K, Gigabyte F2A68HM-S1 motherboard). 

![screenshot_2017-12-21_20-18-39](https://user-images.githubusercontent.com/16281362/34271539-ee30c71c-e68c-11e7-908d-848cde11f005.png)

**Comment by erikdubois** [comment]
Thought it was weather conky....
it is just the temperature of your system
`sensors | grep 'Core 0' | awk {'print $3'}`
You need to change that line.

**Comment by foo4foo** [comment]
I don't mind this lack of information on this conky. I just thought it would be cool if it worked in the first place.

**Comment by erikdubois** [comment]
It will never work on all hardware out there. 
You must realize that.
type sensors in the terminal and change the script so it works on your system.
