### ISSUE TITLE
Acros theme don't show MB product and manufacturer informations

### ISSUE THREAD

**Issue by sardus-X** [erikdubois/Aureola#22]
Hi,
Installed Aureola Conky Collection on Linux Mint 18.1 Xfce but running Acros theme the informations about MotherBoard Model and Manufacturer are missing. Dmidecode (3.0) is installed with "sudo chmod u+s /usr/sbin/dmidecode".
How can i fix it?
Thanks in advance for Your help

**Comment by sardus-X** [comment]
Update:
launching from terminal:
`dmidecode -t 2
`
I get the following message
`# dmidecode 3.0
Getting SMBIOS data from sysfs.
SMBIOS 3.1.1 present.
SMBIOS implementations newer than version 3.0 are not
fully supported by this version of dmidecode.
`
I think I'll have to try to install dmidecode 3.1 building from source (v. 3.1 package for ubuntu 16.04 is not in the repositories)

**Comment by erikdubois** [comment]
support has stopped
