### ISSUE TITLE
Lazuli Blue Colors

### ISSUE THREAD

**Issue by ThirstyThursten** [erikdubois/Aureola#25]
Hello Erik!
I really love what you did here, it's easy to use and very amazing!

I have a question though.. I am looking into the Lazuli 8core theme, I love it, but I would would like to have the old version (at least I guess it's the old version) with the blue letters like the one in [this](https://camo.githubusercontent.com/1183ef5dbe769224946da877f69662e31859ca26/687474703a2f2f692e696d6775722e636f6d2f734974793642442e6a7067) picture in the readme.
Is it possible you could share the other configuration with me/us?
Thanks in advance!
Greets,
Thursten van der Werff

**Comment by arcolinuxz** [comment]
if I posted it once on github.

then go back in time in the commits and you can find it
