### ISSUE TITLE
Color Change

### ISSUE THREAD

**Issue by CybernetiX-S3C** [erikdubois/Aureola#26]
I love your themes. I dont have a real BIG issue, so to speak. But i do have a question.
![2018-12-29_15-35](https://user-images.githubusercontent.com/39076455/50541981-844e8000-0b7f-11e9-93f3-27d27d1ee9be.png)

I am using the gambodekuno dark. I want to Change the color of the Date, without effecting the entire setup. I have been looking through all of your files. I must have missed something.

For example, in my pic I want to change the time to something like silver or white, and the output for all the modules the same matching color

Thanks.

**Comment by erikdubois** [comment]
without testing it 
checking the code
would this line change the color of the font?
line 226
```
	-- font settings
	set_color(1,1);
```
