### ISSUE TITLE
vnstat changed

### ISSUE THREAD

**Issue by TheWyzer** [erikdubois/Aureola#29]
Mr. Dubois,

First let me thank you for putting together this wonderful github page.  I have been using your Lazuli for years now, and have adapted it to my own configuration.

I am just curious if you can help me adapting the new changes to vnstat for "week", which is no longer supported.  I had added the the  "-d 7" which returns values in the shell, however I cannot get those values to grep to the conky.  I have looked at the original Lazuli and mine, and the Month data should show and post, however it doesn't so not sure if the real issue is the grep command?

```
${color1}${font ubuntu:size=11:regular}Week:${font}${color6}${goto 75}${execi 60 vnstat -i enp2s0 -w | grep "current week" | awk '{print $3 $4}'}${alignr 5}${execi 60 vnstat -i enp2s0 -w | grep "current week" | awk '{print $6 $7}'}
${color1}${font ubuntu:size=11:regular}Month:${font}${color6}${goto 75}${execi 60 vnstat -i enp2s0 -m | grep "`date +"%b '%y"`" | awk '{print $3 $4}'}${alignr 5}${execi 60 vnstat -i enp2s0 -m | grep "`date +"%b '%y"`" | awk '{print $6 $7}'}
```
I know this is an old conky, and I believe you posted somewhere that you aren't supporting these anymore.  Well, I kindly ask you to do so in this case, I just want the date to post properly, as it has for a long while until vnstat and conky changed.  I did spend a lot of time updating and "fixing" issues over the years of use, I am just stuck on this one.

Any response and any support will be greatly appreciated.

**Comment by erikdubois** [comment]
thanks these githubs are not maintained anymore - some of them are now part of ArcoLinux

**Comment by erikdubois** [comment]
I checked. It is part of ArcoLinux and it will get a fix there

**Comment by erikdubois** [comment]
no week available anymore
added yesterday
