### ISSUE TITLE
album art for spotify part

### ISSUE THREAD

**Issue by ahjolinna** [erikdubois/Aureola#3]
do u think it would be possible to add album art in the empty space @ the Spotify part in the conf

**Comment by erikdubois** [comment]
made a new conky for you online named acros
follow me on google plus you will see the latest editions there

**Comment by erikdubois** [comment]
see acros conky

**Comment by ahjolinna** [comment]
Im already following you in g+ (also sended a hangouts invite), but I dont use it that often...anyway the the spotify thing doesnt work for me, I get this error: 

```
/home/ahjolinna/.config/conky/spotify-cover.sh: line 16: cover.txt: No such file or directory
/home/ahjolinna/.config/conky/spotify-cover.sh: line 22: [: https://open.spotify.com/image/7dc09be2030c957d4c4e0a00e2880aeefd42093b: unary operator expected
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
conky: Unable to load image '/home/ahjolinna/.config/conky/last_album_pic.png'


```

.......and yes I have those files in that directory

**Comment by erikdubois** [comment]
Check out the update
problem solved earlier that day

thanks

erik

**Comment by ahjolinna** [comment]
I still get this error

```
/home/ahjolinna/.config/conky/spotify-cover.sh: line 22: [: https://open.spotify.com/image/f0c2f5c341af3f8d121ece5b0a4a6e282dc20ed6: unary operator expected
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]

```

**Comment by ahjolinna** [comment]
is there any app that you use for this that I'm missing, I notice that I didnt have vnstat for the network stuff for "Lazuli & Sparki"

**Comment by erikdubois** [comment]
on what operating system are you working?
there is an installation script also in the folder. Those are all the programs I use.
I see dmidecode should be installed and sudo rights (see script)

acros conky spotify is working here on archlinux and linux mint

**Comment by ahjolinna** [comment]
I use chakraOS, I did check that script and installed them... 

PS. I made small fork that combined "Lazuli/Sparki" & acros, and made pkgbuild to ccr (not yet uploaded) for people to install it because some wanted it, yeah I know its not that great/ready yet

https://github.com/ahjolinna/conky-conf

**Comment by erikdubois** [comment]
I have been working on the script of acros and the installation script 
On my end everything works.
There are more checks and dependancies in the script.
Still sensors to add to the checks...

**Comment by ahjolinna** [comment]
weird....if I  execute the "spotify-cover.sh" bash script manually, it works :S

**Comment by ahjolinna** [comment]
hahaha...shit...damn we are blind, or at least I am..
its always the same mistakes, the damn quotes " "
`if [ "$new_cover" != "$old_cover" ]`   <--that fixed it

sigh...now back to sleep...its only 3:30AM :D

**Comment by erikdubois** [comment]
now i see your solution 

here is mine
if [[ $new_cover != $old_cover ]]
