### ISSUE TITLE
spotify album art thing doesn't work & vnstat commands/output have changed

### ISSUE THREAD

**Issue by ahjolinna** [erikdubois/Aureola#30]
what I have been reading Spotify had made a change with the latest version that broke old "mpris way" of getting the album art in your script.

I fixed with this `new_cover=$(playerctl metadata mpris:artUrl | sed "s/open\.spotify\.com/i.scdn.co/")`
(you need playerctl pkgs installed for it to work)

It seems like its a Spotify issue. They have probably moved or removed all the images from https://open.spotify.com/image/{art-address}.

-----

when it comes to vnstat ....I haven't  checked much about it but the outputs are nowday's way different so you won't see anything on conky

**Comment by erikdubois** [comment]
be my guest and change the code

no maintenance done by me

**Comment by qmeeus** [comment]
I guess it's not the case for all of them... Gambodekuno works fine on manjaro, both spotify and vnstat...
