### ISSUE TITLE
Month network data error

### ISSUE THREAD

**Issue by J0hnnyD03** [erikdubois/Aureola#31]
the data acquired from the use of the network in the month, are showing with the borders of the visualization brought from the command vnstat -i

![Screenshot from 2021-05-07 11-54-36](https://user-images.githubusercontent.com/44574545/117468531-28544d00-af2b-11eb-8f5b-ea0373386787.png)

how to solve this????

**Comment by erikdubois** [comment]
by comparing code from lazuli conky 

https://github.com/arcolinux/arcolinux-conky-collection/blob/master/etc/skel/.config/conky/AUR-Lazuli.conkyrc

this is not maintained
