### ISSUE TITLE
2nd font for asian/jpn's characters (spotify)

### ISSUE THREAD

**Issue by ahjolinna** [erikdubois/Aureola#5]
small thing I did notice now when playing music, some of the artist/song have asian characters and they need "asian fonts" to show...they wont work with SourceSansPro alone, for asian characters you need [SourceHanSans ](https://github.com/adobe-fonts/source-han-sans), it support at least "CN, JP, KR, TWHK".

**Comment by erikdubois** [comment]
support has stopped
