### ISSUE TITLE
Linux Mint 18 / Cinnamon Conky Windows above desktop icons

### ISSUE THREAD

**Issue by abdupattoh** [erikdubois/Aureola#7]
Hi - 

Really nice suite you have put together that I am trying out for the first time.  I am running Linux Mint 18 with the Cinnamon desktop, and in your scripts conky is above all the desktop icons, so the desktop is unusable.  I expect most people still want to use their desktop.

Changing the own_window_type to "desktop" in the conky.conf made it work the way I wanted.

**Comment by erikdubois** [comment]
i have added this line in every config
own_window_type = 'normal',-- # options are: normal/override/dock/desktop/panel

it is up to the end-user to see what settings work best for every distro.
