### ISSUE TITLE
weather info thing doesnt work

### ISSUE THREAD

**Issue by ahjolinna** [erikdubois/Aureola#8]
it seems http://weather.noaa.gov/pub/data/observations/metar/stations/ is no longer available

**Comment by erikdubois** [comment]
i do not have this in my conkies. Do I?

**Comment by ahjolinna** [comment]
well for example: https://github.com/erikdubois/Aureola/blob/master/lazuli/conky.conf#L111

**Comment by erikdubois** [comment]
i omitted the weather lines all together.
it is not the first time weather services fail us... 
I should have know better than to include it.

**Comment by ahjolinna** [comment]
I understand, anyway I think this is the best weather app there is https://www.windyty.com/

**Comment by ahjolinna** [comment]
I also use this on my sailfishOS phone and Sony uses it also in their own weather app: www.accuweather.com

**Comment by erikdubois** [comment]
windyty looks very nice
did not know that one
